export default [
  [ /\,/g, 'comma' ],
  [ /-/g, 'dash' ],
  [ />/g, 'greater' ],
  [ /</g, 'less' ],
  [ /§/g, 'section' ],
  [ /:/g, 'colon' ],
  [ /%/g, 'percent' ],
  [ /\|/g, 'vertical bar' ],
  [ /»/g, 'right double angle bracket' ],
  [ /~/g, 'tilde' ],
  [ /\//g, 'slash'],
  [ /\&/g, 'and'],
  [ /\+/g, 'plus'],
  [ /\@/g, 'at'],
  [ /\[/g, 'left bracket'],
  [ /\]/g, 'right bracket'],
  [ /\{/g, 'left brace'],
  [ /\}/g, 'right brace'],
  [ /\$/g, 'dollars'],
  [ /\*/g, 'star'],
  [ /\#/g, 'number'],
  [ /\(/g, 'left paren'],
  [ /\)/g, 'right paren'],
  [ /\=/g, 'equals'],
  [ /\'/g, 'quote'],
  [ /([0-9]+)([,])/g, '$1'],
  [ /_/g, 'underline'],
  [ /\u20ac/g, 'euros'], //Handle characters in UTF-8 pages
  [ /\u2022/g, 'bullet'],
  [ /\u00a3/g, 'pounds'],
  [ /\u0024/g, 'dollars'],
  [ /\u00a9/g, 'copyright'],
  [ /\u00a9/g, 'trade mark'],
  [ /\u00ab/g, 'left double angle bracket'],
  [ /\u00bb/g, 'right double angle bracket'],
];
