name: CI
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching node_modules
        uses: actions/cache@v1
        with:
          path: ~/cache
          key: {{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            {{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run test -- --coverage
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
